apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: myapp-replicaSet
  labels:
    app: myapp
    type: frontend

spec:
  template:
    metadata:
      name: myapp
      type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  
  replicas: 3
  
  selectors:
    matchLabels:
      app: myapp
      type: front-end
